// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMFoWoIGDsfru0oww9oCWB_Yqve1w2-Pk',
    appId: '1:89757208922:web:e8f1c844381e1f541ba363',
    messagingSenderId: '89757208922',
    projectId: 'jobinterview-79321',
    authDomain: 'jobinterview-79321.firebaseapp.com',
    storageBucket: 'jobinterview-79321.firebasestorage.app',
    measurementId: 'G-SQ9MY1PB2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ5LYrZMuMDtCBv5YYPxt08MlRdbcNtWQ',
    appId: '1:89757208922:android:88c01bab5c488a3b1ba363',
    messagingSenderId: '89757208922',
    projectId: 'jobinterview-79321',
    storageBucket: 'jobinterview-79321.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJWC0cdTwZ86xtqWLjgEIaaSzXFT9hPss',
    appId: '1:89757208922:ios:d20df191b7c224641ba363',
    messagingSenderId: '89757208922',
    projectId: 'jobinterview-79321',
    storageBucket: 'jobinterview-79321.firebasestorage.app',
    iosBundleId: 'com.example.jobInterviewQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJWC0cdTwZ86xtqWLjgEIaaSzXFT9hPss',
    appId: '1:89757208922:ios:d20df191b7c224641ba363',
    messagingSenderId: '89757208922',
    projectId: 'jobinterview-79321',
    storageBucket: 'jobinterview-79321.firebasestorage.app',
    iosBundleId: 'com.example.jobInterviewQuizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMFoWoIGDsfru0oww9oCWB_Yqve1w2-Pk',
    appId: '1:89757208922:web:7bcf826c4468a0091ba363',
    messagingSenderId: '89757208922',
    projectId: 'jobinterview-79321',
    authDomain: 'jobinterview-79321.firebaseapp.com',
    storageBucket: 'jobinterview-79321.firebasestorage.app',
    measurementId: 'G-Z06N3KHFHW',
  );
}
